name:                komodo-base
version:             0.1.0.0
github:              "libscott/hoek"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/cryptoconditions-komodo#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- base58-bytestring
- bytestring
- containers
- cryptonite
- cryptoconditions
- memory
- text
- transformers
- unordered-containers

library:
  source-dirs: src

tests:
  cryptoconditions-komodo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - komodo-base
